// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ7GhCZJzqRxeJSPrtO7IpROD--SApwgc',
    appId: '1:208045360497:android:cc36abeece34d1a53b62d0',
    messagingSenderId: '208045360497',
    projectId: 'up-invest-app',
    storageBucket: 'up-invest-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA22iSp-wkbU_cUGHKhr158pP55gmdw6lA',
    appId: '1:208045360497:ios:1767b5a2feff95343b62d0',
    messagingSenderId: '208045360497',
    projectId: 'up-invest-app',
    storageBucket: 'up-invest-app.appspot.com',
    androidClientId: '208045360497-v4kvk1nh4a97q1i3o9l2jqrib466oqgq.apps.googleusercontent.com',
    iosClientId: '208045360497-09cgdpjvrg3qeuco2jiu5n8v001jt5eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.upInvestFront',
  );
}
